apiVersion: v1
kind: Namespace
metadata:
  name: link-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: link-proxy-access
  namespace: link-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: link-proxy-pod-access
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: link-proxy-pod-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: link-proxy-pod-access
subjects:
- kind: ServiceAccount
  name: link-proxy-access
  namespace: link-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: link-proxy-node-access
  namespace: blimp-system
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: link-proxy-node-access
  namespace: blimp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: link-proxy-node-access
subjects:
- kind: ServiceAccount
  name: link-proxy-access
  namespace: link-proxy
